/**
 * SYSTEM CONSTANTS & RBAC POLICY
 * Centralized source of truth for Roles, Permissions, and Status codes.
 */

export const ROLES = {
    SUPER_ADMIN: "SUPER_ADMIN",
    ADMIN: "ADMIN",
    DOCTOR: "DOCTOR",
    NURSE: "NURSE",
    RECEPTIONIST: "RECEPTIONIST",
    PATIENT: "PATIENT",
};
  
/**
 * STAFF_ROLES_ARRAY
 * Helper used for administrative filtering and staff-only middleware logic.
 */
export const STAFF_ROLES_ARRAY = [
    ROLES.SUPER_ADMIN,
    ROLES.ADMIN,
    ROLES.DOCTOR,
    ROLES.NURSE,
    ROLES.RECEPTIONIST,
];

export const PERMISSIONS = {
    // User Management
    USER_READ: "USER_READ",
    USER_CREATE: "USER_CREATE",
    USER_UPDATE: "USER_UPDATE",
    USER_DELETE: "USER_DELETE",
  
    ROLE_READ: "ROLE_READ",
    ROLE_CREATE: "ROLE_CREATE",
    ROLE_UPDATE: "ROLE_UPDATE",
    ROLE_DELETE: "ROLE_DELETE",
  
    PERMISSION_READ: "PERMISSION_READ",
    PERMISSION_CREATE: "PERMISSION_CREATE",
    PERMISSION_UPDATE: "PERMISSION_UPDATE",
    PERMISSION_DELETE: "PERMISSION_DELETE",
  
    DOCTOR_DASHBOARD_VIEW: "DOCTOR_DASHBOARD_VIEW",
    DOCTOR_SETTINGS_MANAGE: "DOCTOR_SETTINGS_MANAGE",
    NURSE_DASHBOARD_VIEW: "NURSE_DASHBOARD_VIEW",
    NURSE_SETTINGS_MANAGE: "NURSE_SETTINGS_MANAGE",
    PATIENT_DASHBOARD_VIEW: "PATIENT_DASHBOARD_VIEW",
    PATIENT_SETTINGS_MANAGE: "PATIENT_SETTINGS_MANAGE",
    RECEPTIONIST_DASHBOARD_VIEW: "RECEPTIONIST_DASHBOARD_VIEW",
    RECEPTIONIST_SETTINGS_MANAGE: "RECEPTIONIST_SETTINGS_MANAGE",

    FHIR_EXPORT: 'FHIR_EXPORT',
    BREAK_GLASS_REQUEST: 'BREAK_GLASS_REQUEST',
    BREAK_GLASS_APPROVE: 'BREAK_GLASS_APPROVE',
    BREAK_GLASS_REVOKE:'BREAK_GLASS_REVOKE',
    BREAK_GLASS_REJECT: 'BREAK_GLASS_REJECT',
    BREAK_GLASS_EXPIRE: 'BREAK_GLASS_EXPIRE',
    BREAK_GLASS_READ: 'BREAK_GLASS_READ',
    // Patients
    PATIENT_READ: "PATIENT_READ",
    PATIENT_CREATE: "PATIENT_CREATE",
    PATIENT_UPDATE: "PATIENT_UPDATE",
    PATIENT_DELETE: "PATIENT_DELETE",
  
    PRESCRIPTION_READ: "PRESCRIPTION_READ",
    MEDICAL_RECORD_READ: "MEDICAL_RECORD_READ",
    BILLING_VIEW: "BILLING_VIEW",
  
    // Doctors
    DOCTOR_READ: "DOCTOR_READ",
    DOCTOR_CREATE: "DOCTOR_CREATE",
    DOCTOR_UPDATE: "DOCTOR_UPDATE",
    DOCTOR_DELETE: "DOCTOR_DELETE",
    CLINICAL_NOTE_CREATE: "CLINICAL_NOTE_CREATE",
    CLINICAL_NOTE_READ: "CLINICAL_NOTE_READ",
    CLINICAL_NOTE_UPDATE: "CLINICAL_NOTE_UPDATE",
    CLINICAL_NOTE_DELETE: "CLINICAL_NOTE_DELETE",

    // Doctors-Patients
    DOCTOR_PATIENT_READ: "DOCTOR_PATIENT_READ",
  
    // Nurses
    NURSE_READ: "NURSE_READ",
    NURSE_CREATE: "NURSE_CREATE",
    NURSE_UPDATE: "NURSE_UPDATE",
    NURSE_DELETE: "NURSE_DELETE",

    VITAL_CREATE: "VITAL_CREATE",
    VITAL_READ: "VITAL_READ",
    VITAL_DELETE:'VITAL_DELETE',
    VITAL_UPDATE: 'VITAL_UPDATE',

    BREAK_GLASS_REQUEST_READ: 'BREAK_GLASS_REQUEST_READ',
    BREAK_GLASS_REQUEST_APPROVE: 'BREAK_GLASS_REQUEST_UPDATE',
    BREAK_GLASS_REQUEST_CREATE: 'BREAK_GLASS_REQUEST_CREATE',
    
    // Receptionists
    RECEPTIONIST_READ: "RECEPTIONIST_READ",
    RECEPTIONIST_CREATE: "RECEPTIONIST_CREATE",
    RECEPTIONIST_UPDATE: "RECEPTIONIST_UPDATE",
    RECEPTIONIST_DELETE: "RECEPTIONIST_DELETE",
  
    // Appointments
    APPOINTMENT_READ: "APPOINTMENT_READ",
    APPOINTMENT_CREATE: "APPOINTMENT_CREATE",
    APPOINTMENT_UPDATE: "APPOINTMENT_UPDATE",
    APPOINTMENT_DELETE: "APPOINTMENT_DELETE",
  
    // Bills
    BILL_READ: "BILL_READ",
    BILL_CREATE: "BILL_CREATE",
    BILL_UPDATE: "BILL_UPDATE",
    BILL_DELETE: "BILL_DELETE",
  
    // Audit & Reports
    AUDIT_READ: "AUDIT_READ",
    REPORT_READ: "REPORT_READ",
    REPORT_GENERATE: "REPORT_GENERATE",
  
    // Metrics & Dashboard
    METRICS_READ: "METRICS_READ",
    DASHBOARD_VIEW: "DASHBOARD_VIEW",
};
  
export const STATUS = {
    SUCCESS: "SUCCESS",
    FAIL: "FAIL",
    ERROR: "ERROR",
    NOTFOUND: "NOTFOUND",
};

export const BILL_STATUS = {
    PAID: "paid",
    UNPAID: "unpaid",
    PENDING: "pending",
    CANCEL: "cancelled",
    PARTIALLY_PAID: "partially_paid",
};

export const AUDIT_ACTIONS = {
    USER_REGISTER: 'USER_REGISTER',
    PROFILE_SELF_UPDATE: 'PROFILE_SELF_UPDATE',
    ADMIN_USER_UPDATE: 'ADMIN_USER_UPDATE',
    ADMIN_USER_DELETE: 'ADMIN_USER_DELETE',
    
    
    USER_LOGIN: 'USER_LOGIN',
    PASSWORD_CHANGE:'PASSWORD_CHANGE',
    USER_LOGOUT: 'USER_LOGOUT',

    CREATE_PERMISSION: 'CREATE_PERMISSION',
    USER_PERMISSION_UPDATE: 'USER_PERMISSION_UPDATE',

    RBAC_ROLE_CREATE: 'RBAC_ROLE_CREATE',
    RBAC_ROLE_DELETE: 'RBAC_ROLE_DELETE',
    RBAC_ROLE_PERMISSIONS_UPDATE:'RBAC_ROLE_PERMISSIONS_UPDATE',

  PATIENT_REGISTRATION: 'PATIENT_REGISTRATION',
    PATIENT_RECORD_UPDATE: 'PATIENT_RECORD_UPDATE',
    PATIENT_RECORD_DELETE: 'PATIENT_RECORD_DELETE',
    
  
    BILL_CREATE: 'BILL_CREATE',
  BILL_UPDATE: 'BILL_UPDATE',
  BILL_PAYMENT: 'BILL_PAYMENT',
    BILL_READ: 'BILL_READ',
    BILL_CANCEL: 'BILL_CANCEL',
  
  APPOINTMENT_CREATE: 'APPOINTMENT_CREATE',
  APPOINTMENT_UPDATE: 'APPOINTMENT_UPDATE',
    APPOINTMENT_CANCEL: 'APPOINTMENT_CANCEL',

    CLINICAL_NOTE_CREATE: 'CLINICAL_NOTE_CREATE',
    CLINICAL_NOTE_UPDATE: 'CLINICAL_NOTE_UPDATE',
    CLINICAL_NOTE_DELETE: 'CLINICAL_NOTE_DELETE',
    CLINICAL_NOTE_READ: 'CLINICAL_NOTE_READ',
  
    CLINICAL_NOTE_CREATE:'CLINICAL_NOTE_CREATE',
    CLINICAL_NOTE_CREATE: 'CLINICAL_NOTE_CREATE',
    CLINICAL_NOTE_CREATE: 'CLINICAL_NOTE_CREATE',
    
    VITAL_SIGN_RECORD: 'VITAL_SIGN_RECORD',
    VITAL_SIGN_UPDATE: 'VITAL_SIGN_UPDATE',
    VITAL_SIGN_DELETE: 'VITAL_SIGN_DELETE',
    
    BREAK_GLASS_REQUEST: 'BREAK_GLASS_REQUEST',
    BREAK_GLASS_APPROVE: 'BREAK_GLASS_APPROVE',
    BREAK_GLASS_REJECT: 'BREAK_GLASS_REJECT',
    BREAK_GLASS_REVOKE:'BREAK_GLASS_REVOKE',
    BREAK_GLASS_EXPIRE: 'BREAK_GLASS_EXPIRE',
    BREAK_GLASS_READ: 'BREAK_GLASS_READ',

    BREAK_GLASS_SESSION_REGISTER: 'BREAK_GLASS_SESSION_REGISTER',
    BREAK_GLASS_VIEW: 'BREAK_GLASS_VIEW',
     

    EXPORT_FHIR: 'EXPORT_FHIR',
    
    
    // Generic fallback
    VIEW: 'VIEW',
    CREATE: 'CREATE',
    UPDATE: 'UPDATE',
    DELETE: 'DELETE'

};