version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: busade_emr_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: busade_emr_demo
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: emr_backend
    restart: always
    env_file:
      - ../.env
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    command: >
      sh -c "npm run seed && npm run dev"

volumes:
  postgres_data:
