version: "3.9"

services:
  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.dev
    container_name: busade-emr-backend-dev
    env_file:
      - ../.env.docker.dev
    ports:
      - "5000:5000"
    volumes:
      - ../src:/usr/src/app/src
      - ../package.json:/usr/src/app/package.json
      - ../package-lock.json:/usr/src/app/package-lock.json
      - /usr/src/app/node_modules
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: busade-emr-db-dev
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: busade_emr_demo_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro

volumes:
  postgres_data_dev:
