FROM node:20

WORKDIR /usr/src/app

# Install dependencies
COPY package*.json ./
RUN npm install

# Install dev helper
RUN npm install -g nodemon

# Copy source (for dev we will mount src via compose)
COPY . .

EXPOSE 5000
CMD ["npm", "run", "dev"]
