services:
  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: busade-emr-backend-dev
    command: npm run local
    ports:
      - "5000:5000"
    volumes:
      - ../:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - ../.env.dev
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    container_name: busade-emr-db-dev
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: busade_emr_demo_db
      DB_HOST: db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data

volumes:
  postgres_data_dev:
