version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: busade_emr_postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: ${NODE_ENV}
    container_name: busade_emr_backend
    restart: always
    env_file:
      - .env.${ENV}
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    volumes:
      - ./src:/usr/src/app/src   # Live reload in dev
    command: >
      sh -c "if [ '${ENV}' = 'dev' ]; then npm run dev; else node src/server.js; fi"

volumes:
  postgres_data:
